/**
 * @property {string} id - unique id used to identify an object, mainly for setting purpouses
 * @property {boolean} carried - the object is carried by the player
 * @property {string} location - the name of the scene where the object is located
 * @property {string[]} actions - the actions allowed on the object
 * @property {boolean} [false] pickable - the object can be picked
 * @property {boolean} [false] show - the object is listed in the scene description
 * @property {string} description - the detailed description returend when the player looks at the object
 * @property {boolean} actionable - wether the object can be used or not
 */
const objects = [
    {
        term: 'cheese',
        id: 'cheese-prisoner',
        label: 'un pezzo di formaggio ammuffito',
        actions: ['eat', 'use', 'spread'],
        carried: true,
        show: true,
        pickable: true,
    },
    {
        term: 'mirror',
        location: 'prisoner',
        id: 'mirror-prisoner',
        label: 'un frammento di specchio',
        actions: ['use', 'insert'],
    },
    {
        term: 'rope',
        location: 'prisoner',
        id: 'rope-prisoner',
        label: 'la corda che ti teneva legato',
        description: 'è una corda molto robusta che ti cinge la vita',
        actions: ['use', 'insert'],
        show: false,
        actionable: false,
        pickable: true,
    },
    {
        term: 'door',
        location: 'prisoner',
        id: 'door-prisoner',
        description: `È una porta di ferro. Sembra decisamente resistente. 
        Al centro c'è uno spioncino che i tuoi carcerieri usavano per passarti il cibo. Se di cibo si può parlare.
        Ma ovviamente è troppo piccolo perché tu ci possa passare.`,
        show: false,
        actionable: false,
    },
    {
        term: 'jailer',
        id: 'jailer-jailer',
        location: 'jailer',
        label: 'il carceriere stecchito',
        description: `È accasciato a terra. La bocca contorta in una smorfia di dolore.
        È vestito solo con dei luridi calzoncini mezzi strappati.
        Alla vita ha una rozza cintura, fatta con un pezzo di corda, da cui pende un mazzo di chiavi`,
        show: true,
    },
    {
        term: 'key',
        location: 'jailer',
        id: 'keys-jailer',
        label: 'un mazzo di chiavi unte',
        description: 'Sono delle chiavi mezze arruginite e un po\' storte, chissà cosa aprono.',
    },
    {
        term: 'shelf',
        location: 'hardware',
        id: 'shelf-hardware',
        label: 'uno scaffale pieno di chiodi storti e attrezzi arrugginiti',
        description: 'Lo scaffale è pieno di ciarpame inutile, ma in un angolo vedi un coltello apparentemente ancora in buono stato.',
        show: true,
    },
    {
        term: 'knife',
        location: 'hardware',
        id: 'knife-hardware',
        label: 'un coltello',
        description: 'È un coltello un po\' malmesso ma ancora utilizzabile.',
    },
    {
        term: 'sail',
        location: 'sails',
        id: 'sail-sails',
        label: 'un mucchio di vele accatastate',
        description: 'Sono mucchi di vele sporche e lacere, non sembrano molto utili.',
        show: true,
    },
    {
        term: 'legs',
        location: 'legs',
        id: 'legs-legs',
        label: 'la collezione di gambe di legno dei pirati',
        description: 'Sono tutte piuttosto malmesse.',
        show: true,
    },
    {
        term: 'leg',
        location: 'legs',
        id: 'leg-legs',
        label: 'una gamba di legno',
        description: 'È una solidissima gamba di legno',
        show: true,
        pickable: true,
    },
    {
        term: 'coffers',
        location: 'coffers',
        id: 'coffers-coffers',
        label: 'un ammasso di forzieri',
        description: 'Sono un mucchio di forzieri, purtroppo tutti vuoti.',
        show: true,
    },
    {
        term: 'coffer',
        location: 'coffers',
        id: 'coffer-coffers',
        label: 'un forziere',
        description: 'È un forziere vuoto.',
        actions: ['jump'],
        pickable: true,
    },
    {
        term: 'ladder',
        location: 'ropes',
        id: 'ladder-ropes',
        label: 'una scala di corda',
        description: 'È una scala di corda arrotolata, sembra messa bene.',
        pickable: true,
        show: true,
    },
    {
        term: 'hole',
        location: 'exit0',
        id: 'hole-exit0',
        label: 'un boccaporto',
        description: 'Probabilmente è il passaggio che permette di uscire dalla stiva. Ai bordi vedi 2 ganci di ferro.',
        show: true,
    },
    {
        term: 'pirate',
        location: 'sails',
        id: 'sails-pirate',
        label: 'un feroce pirata',
        description: 'Ha un rivolo di sangue che gli esce dalla bocca, barcolla ma ti si avventa contro con un coltello.',
        show: true,
        pickable: true,
    },
    {
        term: 'stove',
        location: 'kitcken',
        id: 'kitcken-stove',
        label: 'la stufa per cucinare',
        description: 'È una stufa a legna con 2 forni e una piastra superiore dove appoggiare le pentole.',
        show: true,
    },
    {
        term: 'cooker',
        location: 'kitcken',
        id: 'kitcken-cooker',
        label: 'una piastra per cucinare',
        description: 'È una piastra sui cui si possono appoggiare le pentole per cucinare.',
    },
    {
        term: 'oven',
        location: 'kitcken',
        id: 'kitcken-oven',
        label: 'la stufa ha 2 piccoli forni',
        description: 'Provi ad aprire lo sportello, ma dentro non c\'è nulla.',
    },
    {
        term: 'cookware',
        location: 'kitcken',
        id: 'kitcken-cookware',
        label: 'pentole e altri attrezzi da cucina',
        description: 'Sono pentole, coperchi, mestoli e cucchiai, tutti ordinatamente appesi ad un filo.',
        show: true,
    },
    {
        term: 'barrels',
        location: 'galley',
        id: 'galley-barrels',
        label: 'barili di carne scoperchialata',
        description: 'sono barili pieni di carne sotto sale. Sembrano decisamente appetitosi, soprattutto dopo 2 giorni di digiuno...',
        show: true,
    },
    {
        term: 'meat',
        location: 'galley',
        id: 'galley-meat',
        label: 'carne salata',
        description: '',
        actions: ['eat'],
    },
    {
        term: 'carboys',
        location: 'galley',
        id: 'galley-carboys',
        label: 'damigiane di vino',
        description: 'Sono damigiane piene di vino. Per la verità alcune sono decisamente vuote, si vede che i pirati ci davano dentro.',
        show: true,
    },
    {
        term: 'wine',
        location: 'galley',
        id: 'galley-wine',
        label: 'vino',
        description: '',
        actions: ['drink'],
    },
    {
        term: 'boxes',
        location: 'galley',
        id: 'galley-boxes',
        label: 'scatole di gallette',
        description: 'Sono scatole di legno piene di gallette salate. Guardando meglio noti che sono piene di vermi. Purtroppo nei lunghi viaggi per mare capita.',
        show: true,
    },
    {
        term: 'cookies',
        location: 'galley',
        id: 'galley-cookies',
        label: 'gallette',
        description: '',
        actions: ['eat'],
    },
    {
        term: 'goatskin',
        location: 'galley',
        id: 'galley-goatskin',
        label: 'otri piene d\'acqua',
        description: 'Sono otri che custodiscono la riserva di acqua della nave.',
        show: true,
    },
    {
        term: 'water',
        location: 'galley',
        id: 'galley-water',
        label: 'acqua',
        description: '',
        actions: ['drink'],
    },
];
// Ci sono barili di carne salata, damigiane di vino, scatole di gallette e otri piene d\'acqua.
module.exports = objects;
